### ISSUE TITLE
VSC 1.10.2 minimap color not set by theme

### ISSUE THREAD

**Issue by LIII-XXII** [kobalicek/reloaded-themes#1]
Please have a look at the attached screenshot -- code minimap background color on VSC1.10.2 is set to white, on the black theme.

EDIT: can't attach screenshot, here's a link: https://www.noelshack.com/2017-10-1489052882-2017-03-09-10h44-50.png

**Comment by kobalicek** [comment]
Thanks for the report, the theme is missing a background color, I initially assumed that VSCode will use the default of UI theme. I will fix it.

**Comment by kobalicek** [comment]
I just released a new version that should have this issue fixed, including some minor color tweaks as well (as initial support for light theme). Thanks again for the bug report.

**Comment by LIII-XXII** [comment]
It is fixed now, thank you!
